In [1]:
import numpy as np
# Outlier = Unusual value 
price = np.array([100,200,300,100000])
# HEre 100000  is outliers
print(np.mean(price))
# output = 25150.0
    # which is out of range and unmatched

25150.0

In [2]:
# Three types of outliers
    # 1. Global or on point outlier
    # 2. Contexual outlier
    # 3. Collective outlier

In [3]:
# To find outlier

    # IQR Method 
    # z-score method
    # box plot

In [4]:
# QUARTILES ---> Quarter division

    # Q1 --> 25% below
    # Q2 --> Median/ below 50% , Above 50%
    # Q3 --> Below 75% , Above 75%

In [5]:
salary = np.array([1000,2000,3000,5000,7000,8000,9000,12000])
# Q2
np.median(salary)

np.float64(6000.0)

In [6]:
# Q1
np.percentile(salary,25)

np.float64(2750.0)

In [7]:
#  Q1
np.quantile(salary,0.25)

np.float64(2750.0)

In [8]:
# Q3
np.percentile(salary,75)

np.float64(8250.0)

In [9]:
#  Q3
np.quantile(salary,0.75)

np.float64(8250.0)

In [10]:
# IQR method
# IQR = Q3 - Q1 =  8250.0 -  2750.0  = 5500.0

In [11]:
# 1. lower bound = Q1 - 1.5  * IQR =  -5500.0

# 2. Upper bound = Q3 + 1.5 * IQR = 16500.0

In [35]:
import pandas as pd
spd = pd.DataFrame({
    "salary" : [1000,2000,50000,3000,5000,7000,8000,9000,12000,100000]
})

In [36]:
spd

   salary
0    1000
1    2000
2   50000
3    3000
4    5000
5    7000
6    8000
7    9000
8   12000
9  100000

In [37]:
q2 = spd["salary"].quantile(0.5)
q2

np.float64(7500.0)

In [38]:
q1 = spd["salary"].quantile(0.25)
q1

np.float64(3500.0)

In [39]:
q3 = spd["salary"].quantile(0.75)
q3

np.float64(11250.0)

In [40]:
iqr = q3 - q1
iqr

np.float64(7750.0)

In [41]:
# lower_bound
lb = q1 - 1.5 * iqr
lb

np.float64(-8125.0)

In [42]:
# Upper_bound
ub = q3 + 1.5 * iqr
ub

np.float64(22875.0)

In [43]:
outlier = spd[(spd["salary"] < lb) | (spd["salary"] > ub)]
outlier

   salary
2   50000
9  100000