In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("daraz_dataset.csv")

In [4]:
df

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned
499,DZ100500,2026-01-14,Rohit Adhikari,25,Male,Bhaktapur,Sports,Yoga Mat,2,38163,10,68693.40,IME Pay,4,Returned

In [6]:
df.head()

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled

In [9]:
df.shape # (500, 15)

(500, 15)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          500 non-null    str
 1   OrderDate        500 non-null    str
 2   CustomerName     500 non-null    str
 3   Age              500 non-null    int64
 4   Gender           500 non-null    str
 5   District         500 non-null    str
 6   Category         500 non-null    str
 7   Product          500 non-null    str
 8   Quantity         500 non-null    int64
 9   UnitPrice        500 non-null    int64
 10  DiscountPercent  500 non-null    int64
 11  TotalAmount      500 non-null    float64
 12  PaymentMethod    500 non-null    str
 13  Rating           500 non-null    int64
 14  OrderStatus      500 non-null    str
dtypes: float64(1), int64(5), str(9)
memory usage: 58.7 KB

In [11]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerName', 'Age', 'Gender', 'District',
       'Category', 'Product', 'Quantity', 'UnitPrice', 'DiscountPercent',
       'TotalAmount', 'PaymentMethod', 'Rating', 'OrderStatus'],
      dtype='str')

In [12]:
df.describe()

,Age,Quantity,UnitPrice,DiscountPercent,TotalAmount,Rating
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,36.114000,3.116000,25433.808000,10.630000,70063.721000,2.990000
std,10.969853,1.424993,14012.030302,7.304781,52519.872403,1.393479
min,18.000000,1.000000,468.000000,0.000000,478.800000,1.000000
25%,27.000000,2.000000,12581.000000,5.000000,27237.225000,2.000000
50%,36.000000,3.000000,26243.500000,10.000000,55536.500000,3.000000
75%,46.000000,4.000000,37552.000000,16.250000,106513.650000,4.000000
max,55.000000,5.000000,49958.000000,20.000000,229910.000000,5.000000

In [13]:
df.dtypes

OrderID                str
OrderDate              str
CustomerName           str
Age                  int64
Gender                 str
District               str
Category               str
Product                str
Quantity             int64
UnitPrice            int64
DiscountPercent      int64
TotalAmount        float64
PaymentMethod          str
Rating               int64
OrderStatus            str
dtype: object

In [14]:
numeric_columns = [
    'Age',
    'Quantity',
    'UnitPrice', 
    'DiscountPercent',
    'TotalAmount',
    'Rating'
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column],errors="coerce")

In [15]:
df.isnull().sum()

OrderID            0
OrderDate          0
CustomerName       0
Age                0
Gender             0
District           0
Category           0
Product            0
Quantity           0
UnitPrice          0
DiscountPercent    0
TotalAmount        0
PaymentMethod      0
Rating             0
OrderStatus        0
dtype: int64

In [16]:
df["Quantity"]  = df["Quantity"].fillna(df["Quantity"].mean())

In [17]:
df

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned
499,DZ100500,2026-01-14,Rohit Adhikari,25,Male,Bhaktapur,Sports,Yoga Mat,2,38163,10,68693.40,IME Pay,4,Returned

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          500 non-null    str
 1   OrderDate        500 non-null    str
 2   CustomerName     500 non-null    str
 3   Age              500 non-null    int64
 4   Gender           500 non-null    str
 5   District         500 non-null    str
 6   Category         500 non-null    str
 7   Product          500 non-null    str
 8   Quantity         500 non-null    int64
 9   UnitPrice        500 non-null    int64
 10  DiscountPercent  500 non-null    int64
 11  TotalAmount      500 non-null    float64
 12  PaymentMethod    500 non-null    str
 13  Rating           500 non-null    int64
 14  OrderStatus      500 non-null    str
dtypes: float64(1), int64(5), str(9)
memory usage: 58.7 KB

In [19]:
# giving inputs to machine learning
# After data cleaning
    # Feature selection (fs)

In [21]:
features = ["Age", "Quantity", "UnitPrice", "DiscountPercent"]
target = "TotalAmount"

# Super features store garne X, targert store garne Y  banaune 

x = df[features]
y = df[target]

In [22]:
type(x)

pandas.DataFrame

In [23]:
type(y)

pandas.Series

In [ ]:
# we feed in data as a numpy array form
#

In [24]:
x = x.to_numpy()
y = y.to_numpy()

In [25]:
type(x)

numpy.ndarray

In [26]:
type(y)

numpy.ndarray

In [27]:
x.shape

(500, 4)

In [29]:
x.ndim

2

In [30]:
x.nbytes

16000

In [33]:
x

array([[   24,     1, 48898,    10],
       [   52,     2, 33418,    20],
       [   31,     2, 46053,    15],
       ...,
       [   27,     1, 48890,     0],
       [   27,     5,  2468,    10],
       [   25,     2, 38163,    10]], shape=(500, 4))

In [35]:
y

array([ 44008.2 ,  53468.8 ,  78290.1 ,  88175.  ,   3137.85,  37881.  ,
        81298.8 ,  73531.8 , 131042.8 , 157544.  ,  20547.  , 190992.75,
        47976.  ,  50044.5 ,  15718.7 ,   9434.  , 148561.  ,   3631.2 ,
        66684.  ,  53164.  ,  22941.  ,  53085.  ,  61184.  ,  79774.2 ,
        60215.4 , 172632.  , 113823.3 ,    478.8 ,  11974.5 ,  88016.  ,
        77753.7 ,  57855.  , 143462.4 , 129721.5 ,  27498.4 ,  87418.25,
        64588.8 ,  57460.  ,   3800.  ,  19942.  , 140960.  ,  75760.2 ,
       107097.  , 110192.  ,  88832.  , 181484.2 ,  58058.3 ,  14450.85,
        48858.5 ,   9928.8 ,  41391.9 ,   2878.95, 151168.25, 120464.  ,
        44704.8 , 144938.6 , 157923.  ,  19524.  ,  37456.6 ,  28092.  ,
         3894.7 , 110296.  , 204995.  ,  10558.  ,  43080.6 ,   3997.6 ,
        79435.2 , 193885.  , 142463.4 , 111493.65,  34720.  ,  39987.  ,
        15025.  ,  55328.2 ,   1263.6 , 106335.  ,  97287.6 ,  51619.2 ,
        71576.8 ,  40327.2 , 142074.4 ,  68132.  ,  81645.3 ,   4429.35,
        79443.75,  17676.  , 132910.2 ,  14104.8 ,  87184.  ,  31640.  ,
       172880.  ,  40712.4 ,   8495.  ,  23928.  ,   2291.4 ,  26784.35,
        90954.  ,  50105.  , 142465.  , 110248.  ,  28603.  , 107049.6 ,
        21138.3 ,  69912.  , 108108.  ,  74814.45, 107392.8 ,  40307.55,
        52936.  , 113732.  ,  28920.  ,  33755.  ,  75578.2 , 111793.5 ,
        17545.7 , 122662.4 ,  25498.8 ,  43466.4 ,  40353.6 ,  94168.95,
        25806.6 ,  12478.5 ,  24503.4 ,  39049.6 ,  42165.  ,  71390.4 ,
        40165.05, 174484.6 , 140190.  , 126102.4 , 131100.  , 124440.  ,
       218164.5 ,  40142.1 ,  67604.  ,  92300.4 ,  48504.  ,  77356.8 ,
         4446.  ,  44008.75,  15468.  ,  53672.  ,  56877.45,  19160.8 ,
       115689.25,  58068.75,  36761.6 ,  62534.4 , 110404.  ,  45428.  ,
        75325.5 ,  13288.  , 115712.2 ,  10464.  ,  72162.9 , 130806.  ,
        63652.8 , 161899.  , 129608.  , 141309.  ,  37939.2 ,  43510.4 ,
       112477.5 ,  94344.5 ,  19888.8 ,  79085.7 ,  32378.  ,  34548.65,
        70742.  ,  90050.4 ,  27919.95,  90652.8 ,  53499.  ,  77542.8 ,
        35152.6 , 118312.  ,  19949.4 , 116981.25,  25430.  ,  71981.4 ,
       104236.  ,  28084.  ,   5529.6 ,   7586.4 ,  62840.5 ,  90049.  ,
        13043.2 ,  98472.  ,  61718.5 ,  49956.7 , 139778.25,   2451.6 ,
        52835.2 ,  39555.2 ,  44312.75,    586.4 ,  14626.  , 141842.6 ,
        42029.  ,  73070.4 ,  11100.8 ,  72546.75, 167165.25,  71750.4 ,
        75790.8 ,  95088.  ,  76638.  ,  54091.8 ,  47865.75, 113382.  ,
        76374.  ,  62579.2 ,  75250.8 , 113024.  ,  26882.4 , 196980.  ,
        45805.5 ,  44342.4 ,  22783.  ,  51005.5 ,  37082.  , 125582.4 ,
       194885.  , 109471.5 ,  73070.2 , 142052.  ,   6593.4 ,  14284.8 ,
         6150.6 , 177518.25,  51003.  ,  87909.2 ,  84615.8 ,  40971.7 ,
        53844.  ,  49674.  , 124969.65,   7196.8 ,  18775.8 ,   7652.8 ,
        11962.  ,  58507.2 , 127941.  ,  22819.95,  43314.  ,  36968.  ,
       117524.4 ,  16254.  , 144999.  ,  96419.2 ,  78155.2 ,  31052.2 ,
        11450.35,  23253.15,  77729.  ,  10997.6 , 166428.  ,  28470.6 ,
        77238.  ,  69717.  ,  40142.1 ,  11061.9 , 174199.5 ,   9047.2 ,
        84157.65,  72392.85,  73107.2 ,  24969.6 ,  64647.6 ,  70685.7 ,
        29580.85, 220789.5 ,  26339.7 ,  45174.6 , 115045.95,  42085.8 ,
        21753.2 , 204064.75,  47321.4 ,   6242.4 , 154368.5 ,  13168.9 ,
        33892.  ,  40842.9 ,  20535.2 , 150940.  ,  18479.  ,  44162.4 ,
        34330.  ,  10469.  ,  74124.  ,  45787.8 ,  53590.  ,  13006.8 ,
       133385.4 ,  13501.4 ,  34089.8 ,  55593.  ,  84712.5 ,  16200.  ,
       102980.  ,  69435.2 ,  44807.7 ,  12214.4 ,   9671.95,  41678.  ,
       142174.4 ,  63945.  ,  96714.75,  87544.8 , 158512.25,  43132.  ,
        91720.  , 189620.  ,  40385.2 ,   6029.6 ,  14328.  ,   8900.55,
        61587.6 , 127728.  , 116720.  , 138328.  ,  40341.75,  31845.9 ,
        84052.  , 183919.5 , 168376.5 , 155286.  ,  13962.1 , 139046.4 ,
        55480.  ,  85434.45, 212026.5 , 127124.  ,   7554.  ,  20235.1 ,
        21510.95, 119486.4 ,  25020.  ,   5542.3 ,  69896.25,  25707.6 ,
       194778.5 , 142970.  ,   3900.  ,  27355.5 ,  68885.7 ,  39873.6 ,
       104776.  ,  29260.  ,  43748.8 , 122116.  ,  84158.6 ,  41148.  ,
        66355.2 ,  25524.  , 107400.  ,  23138.7 ,  40370.75,   7954.2 ,
        37136.  ,  71344.75,  42381.4 ,  49449.6 ,   6944.8 , 107484.  ,
        24949.2 , 126060.8 ,  32323.2 , 117340.8 ,  26774.8 ,  46774.  ,
        45156.8 ,  43809.6 ,  87012.  , 229910.  ,  40049.1 , 116272.  ,
        22681.25,   6535.  , 151908.  ,  68752.  , 155032.  ,   4216.5 ,
        68216.4 , 112252.  , 136623.6 , 101270.4 ,  42254.1 ,  74856.  ,
        85038.3 ,  18730.2 ,  40192.8 , 176749.2 ,  60966.4 ,  81077.25,
         9824.4 , 146370.  ,   6562.  ,  36732.75,  55110.6 , 115224.  ,
        65838.8 ,  79740.  ,  63372.6 ,  45494.4 , 110894.4 ,  21659.7 ,
        92064.  ,  28371.3 , 208748.25, 151725.6 ,  34599.25,  20128.  ,
       191461.5 ,  78456.  ,  54040.  , 183844.  , 138472.  ,   4463.1 ,
         9493.2 ,  94018.5 ,  45432.8 , 100975.75, 168368.  ,  60855.75,
        41184.  ,  52195.  ,  15175.2 , 190755.  ,  78878.4 ,  20678.  ,
        14557.95,  50907.2 ,  76906.8 , 216260.  ,  99916.  ,  20946.55,
       123222.4 ,  23193.  ,  76948.8 ,  82640.4 ,  77019.  ,  52535.  ,
       169945.5 , 176140.  ,  25232.  ,  29078.4 ,   4100.4 , 163364.4 ,
       141748.  ,  31321.65, 121446.  ,  38959.75, 130051.2 , 123647.8 ,
       122785.05, 143672.  ,  13069.6 ,   9827.  ,  96835.2 ,  22644.  ,
        80822.  ,  83356.8 ,  38952.  , 199875.25,   6984.  ,   9994.  ,
        88041.6 ,  44704.  ,  41908.4 ,   8219.5 , 212082.75,  92691.  ,
        44232.  , 169945.  ,  16564.8 ,  24010.8 ,  44685.  ,  61503.45,
       116002.6 ,  16079.2 ,  21497.55,  24934.4 ,  36180.  ,  47977.6 ,
       170427.6 ,  37116.  ,  91490.6 ,  37476.  ,  72063.  ,  21209.2 ,
         2224.8 ,  27678.4 ,  96176.  , 115060.8 ,  21686.6 ,  48890.  ,
        11106.  ,  68693.4 ])

In [36]:
x[0]

array([   24,     1, 48898,    10])

In [37]:
# Age
x[:,0]

array([24, 52, 31, 42, 32, 28, 20, 34, 50, 47, 18, 28, 23, 31, 55, 33, 24,
       30, 21, 42, 52, 29, 44, 22, 33, 24, 34, 46, 45, 44, 24, 30, 34, 25,
       45, 36, 31, 50, 22, 29, 46, 33, 42, 55, 49, 52, 38, 40, 25, 37, 25,
       41, 55, 19, 18, 36, 40, 31, 18, 48, 21, 51, 31, 48, 30, 54, 20, 20,
       44, 23, 30, 19, 27, 30, 49, 33, 50, 34, 22, 21, 42, 52, 48, 21, 20,
       26, 27, 34, 47, 42, 35, 43, 54, 27, 19, 24, 43, 55, 53, 34, 21, 50,
       45, 43, 38, 44, 37, 25, 43, 25, 43, 40, 49, 48, 41, 54, 29, 39, 55,
       26, 26, 42, 36, 36, 41, 32, 19, 18, 25, 33, 41, 34, 52, 20, 40, 49,
       23, 40, 26, 22, 42, 29, 41, 53, 38, 21, 30, 39, 52, 48, 24, 44, 19,
       48, 54, 26, 20, 28, 19, 32, 25, 21, 39, 31, 43, 52, 32, 30, 29, 47,
       29, 24, 55, 37, 53, 54, 31, 47, 22, 42, 18, 30, 21, 54, 53, 42, 51,
       35, 18, 36, 38, 44, 49, 20, 47, 19, 30, 23, 49, 22, 37, 40, 35, 36,
       37, 24, 23, 28, 30, 26, 33, 47, 27, 20, 43, 54, 36, 24, 33, 19, 52,
       43, 25, 42, 46, 46, 28, 20, 23, 31, 54, 38, 50, 22, 49, 26, 37, 46,
       24, 28, 42, 19, 25, 52, 36, 31, 23, 49, 45, 54, 18, 44, 22, 37, 32,
       21, 24, 43, 46, 28, 37, 18, 30, 19, 33, 51, 35, 28, 33, 29, 30, 41,
       38, 29, 49, 31, 49, 20, 39, 53, 18, 48, 42, 24, 48, 25, 34, 55, 36,
       43, 35, 46, 26, 41, 53, 32, 34, 43, 22, 43, 30, 48, 39, 48, 54, 31,
       42, 33, 36, 43, 20, 46, 24, 24, 53, 23, 36, 35, 44, 42, 38, 33, 49,
       33, 43, 47, 46, 28, 30, 18, 38, 50, 26, 52, 28, 53, 21, 30, 34, 37,
       50, 31, 25, 30, 45, 21, 38, 50, 32, 18, 32, 22, 22, 38, 47, 34, 34,
       43, 54, 31, 34, 40, 35, 48, 50, 36, 55, 42, 20, 51, 32, 51, 52, 41,
       28, 18, 42, 30, 23, 53, 50, 46, 22, 43, 30, 49, 50, 43, 38, 49, 32,
       44, 24, 53, 36, 28, 36, 19, 19, 36, 53, 40, 51, 32, 42, 22, 19, 27,
       27, 33, 37, 31, 55, 40, 42, 54, 36, 41, 44, 24, 22, 35, 30, 28, 38,
       46, 31, 27, 22, 23, 37, 54, 43, 54, 25, 46, 27, 52, 21, 24, 30, 40,
       27, 37, 51, 27, 35, 41, 32, 43, 24, 36, 47, 19, 46, 54, 26, 31, 53,
       37, 47, 26, 51, 54, 25, 36, 54, 47, 39, 25, 37, 39, 42, 37, 25, 53,
       21, 46, 47, 38, 54, 44, 45, 53, 21, 54, 50, 36, 29, 18, 29, 49, 55,
       22, 39, 48, 35, 27, 27, 25])

In [38]:
# DiscountPercentage
x[:,3]

array([10, 20, 15,  0,  5, 10, 10, 15, 15,  0, 10,  5,  0, 10,  5,  0,  5,
       15,  0,  0, 10,  0, 20, 10, 10, 20,  5, 10, 10,  0,  5,  5, 20, 10,
       20, 15, 20, 15,  0,  0, 20, 10,  0,  0, 20,  5,  5, 15,  5, 10, 10,
       15, 15, 20, 20, 15, 10, 20,  5,  0, 15, 20,  0,  0,  5,  5, 20,  0,
       15, 15, 20, 10,  0, 15, 10, 15,  5,  5, 15, 10,  5,  0, 10, 15,  5,
       10, 10, 20, 20,  0,  0, 10,  0, 20, 10, 15,  0,  0,  0,  0,  0, 10,
       10,  0, 10, 15, 20,  5, 20, 20,  0,  0,  5, 10, 15, 20, 10, 10, 20,
       15, 10, 10, 10, 20, 10, 20, 15,  5,  0, 20,  5,  0, 10, 15,  0, 10,
       20, 15,  5, 15,  0,  0,  5, 20, 15,  5, 20, 20, 20,  0,  5,  0, 15,
        0, 10, 10, 20,  5, 20, 10,  5, 20, 10,  5, 20, 10,  0,  5,  0, 20,
       15, 20, 15,  5, 15, 20, 10, 15,  0, 15, 20, 15, 20, 20, 15, 15, 20,
        0, 15,  5, 15, 10, 20, 20,  5, 20,  0,  5,  0, 20, 20,  5, 15, 20,
       10, 20,  0, 10,  5, 10, 10, 20, 10, 20, 20, 20, 10, 20,  0,  5,  0,
       10,  0, 15,  5, 15, 10, 20, 15, 15, 10,  5, 15, 15, 20, 15,  5, 20,
        5, 20,  0, 20,  0, 15,  0,  0, 15,  0,  0, 20, 20, 15,  5,  5,  5,
       20, 10, 10,  0, 15, 15, 15, 10, 20,  5,  5, 20, 20, 15,  5, 15,  5,
        5, 10,  5, 10, 15,  5,  5, 10, 15,  5, 20, 10, 20, 20, 15, 20,  0,
        5,  0, 15,  0, 10, 15,  5,  5, 10, 10, 20,  0, 20,  5, 20,  5,  0,
       15,  0,  5, 10,  5,  0,  0, 20, 15, 20,  0,  5, 15, 20,  0, 20,  5,
        5,  0, 10, 15, 10, 15, 20,  5,  5, 10, 20,  0, 15, 15, 20,  0,  5,
        5, 10,  5, 15,  0, 10, 15, 20,  0, 20, 20, 20,  5, 20, 10, 10, 20,
       15, 15, 10, 20, 15,  5, 10, 20, 20, 15, 20, 20, 15,  5,  0, 20, 20,
        0,  0, 10,  0,  5,  0,  0, 20,  0, 10, 10,  5, 10, 20,  5, 20,  5,
        5, 20, 10, 20, 15, 10, 15,  0, 15, 15, 20,  5,  0,  5, 20, 20, 15,
        0, 15,  5, 10, 15, 20, 10, 20,  0,  5,  5,  5, 10, 15,  5, 15, 15,
       15, 10,  0, 20, 10, 20,  0, 15, 20, 10,  0,  0,  5, 20, 10, 20, 15,
        0,  5,  5,  0,  0, 20, 15, 10, 20, 15,  0, 15,  5, 15, 15,  0, 20,
        0, 20, 20,  0, 20,  0,  5, 10,  5, 20, 20, 15, 15,  5,  0, 20,  0,
       20, 15,  0, 15,  5, 20,  5, 20, 20, 20, 10, 20, 15, 10, 15, 15, 20,
       20, 20, 20,  5,  0, 10, 10])

In [40]:
df.head()

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled

In [42]:
print(x[x[:,0]>30])

[[   52     2 33418    20]
 [   31     2 46053    15]
 [   42     5 17635     0]
 ...
 [   39     4 30055    20]
 [   48     3 47942    20]
 [   35     4  5707     5]]

In [46]:
# finding min age 
print(np.min(x[:,0]))

18