In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split #  for training and testing the data

In [2]:
df = pd.read_csv("student_marks.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     15 non-null     str
 1   StudyHours  15 non-null     float64
 2   FinalMarks  15 non-null     int64
dtypes: float64(1), int64(1), str(1)
memory usage: 492.0 bytes

In [4]:
df

   Student  StudyHours  FinalMarks
0    Aarav         1.0          28
1   Aayush         2.0          35
2     Sita         2.5          40
3      Ram         3.0          45
4   Anisha         3.5          50
5    Rohan         4.0          55
6    Priya         4.5          60
7    Kiran         5.0          65
8    Nabin         5.5          70
9    Suman         6.0          74
10  Alisha         6.5          79
11  Bikash         7.0          84
12  Sabina         7.5          88
13  Roshan         8.0          92
14    Puja         9.0          98

In [6]:
X = df[["StudyHours"]]
Y = df["FinalMarks"]

In [7]:
X = X.to_numpy()
Y = Y.to_numpy()

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 42)

model = LinearRegression()
model.fit(X_train, Y_train)

predicted_Y = model.predict(X_test)

comparision = pd.DataFrame({
    "Actual" : Y_test,
    "Predicted" : predicted_Y
})

comparision

   Actual  Predicted
0      74  73.227474
1      84  82.475628
2      28  26.986706

In [15]:
# Mean square error (MSE)

In [ ]:
study_hrs = 1,2,3,4,5
marks = 10,20,30,40,50

In [22]:
9.25 * 2 + 17.74

36.239999999999995

In [23]:
9.25 * 4 + 17.74

54.739999999999995

In [24]:
9.25 * 6 + 17.74

73.24

In [16]:
1+2+3+4+5

15

In [17]:
15 /5

3.0

In [20]:
30+40+50+60+70

250

In [21]:
250/5

50.0

In [25]:
new_student = np.array([
    [2],
    [4],
    [6],
    [8],
    [10]
])

marks_prediction = model.predict(new_student)
marks_prediction

array([ 36.23485968,  54.73116691,  73.22747415,  91.72378139,
       110.22008863])

In [ ]:
# y  = mx + c
# y = 9.25 * x +  17.74