In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [12]:
# df = pd.DataFrame({
#     "StudyHours": [1,2,3,4,5],
#     "Result": [0,0,0,1,1]
# })

In [4]:
df = pd.read_csv("student_binary_classification.csv")

In [5]:
df

    StudyHours Result
0          1.0   Fail
1          2.0   Fail
2          2.5   Fail
3          3.0   Fail
4          3.5   Fail
5          4.0   Pass
6          4.5   Pass
7          5.0   Pass
8          5.5   Pass
9          6.0   Pass
10         7.0   Pass
11         8.0   Pass

In [6]:
df.head()

   StudyHours Result
0         1.0   Fail
1         2.0   Fail
2         2.5   Fail
3         3.0   Fail
4         3.5   Fail

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudyHours  12 non-null     float64
 1   Result      12 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 324.0 bytes

In [7]:
df.Result = df["Result"].map({
    "Fail": 0,
    "Pass": 1
})

In [8]:
X = df[["StudyHours"]]
y = df["Result"]

In [9]:
df

    StudyHours  Result
0          1.0       0
1          2.0       0
2          2.5       0
3          3.0       0
4          3.5       0
5          4.0       1
6          4.5       1
7          5.0       1
8          5.5       1
9          6.0       1
10         7.0       1
11         8.0       1

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
model = DecisionTreeClassifier(
    criterion="gini"
)

In [13]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [18]:
print(model.tree_.threshold)

[ 3.75 -2.   -2.  ]

In [23]:
new_student =  pd.DataFrame({
    "StudyHours":[3,4,5,9,1]
})

In [24]:
prediction = model.predict(new_student)

In [25]:
prediction

array([0, 1, 1, 1, 0])

In [28]:
df = pd.read_csv("student_multiclass_multiple_features.csv")

In [29]:
df

    Student  StudyHours  Attendance  PreviousMarks   Result
0     Aarav           1          55             28     Fail
1      Sita           2          60             32     Fail
2       Ram           2          65             36     Fail
3    Anisha           3          70             40     Fail
4     Rohan           3          72             43     Fail
5     Priya           4          75             48  Average
6     Kiran           4          78             52  Average
7     Nabin           5          80             56  Average
8     Suman           5          82             60  Average
9    Alisha           5          84             63  Average
10   Bikash           6          86             67     Good
11   Sabina           6          88             70     Good
12   Roshan           6          90             73     Good
13     Puja           7          91             76     Good
14   Manish           7          92             79     Good
15     Rita           7          93             82     Good
16    Deepa           8          94             84     Good
17   Sanjay           8          95             87     Good
18   Kushal           8          96             89     Good
19   Aakash           9          97             91     Good
20     Bina           9          90             75     Good
21  Nischal           9          94             85     Good
22    Rekha          10          98             93     Good
23    Sagar          10          99             95     Good
24     Mina          10          96             90     Good

In [30]:
df.columns

Index(['Student', 'StudyHours', 'Attendance', 'PreviousMarks', 'Result'], dtype='str')

In [31]:
X = df[['StudyHours', 'Attendance', 'PreviousMarks']]
y = df["Result"]

In [33]:
model = DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

In [34]:
model.fit(X,y)

DecisionTreeClassifier(random_state=42)

In [35]:
new_student = pd.DataFrame({
    'StudyHours':[10], 'Attendance':[88], 'PreviousMarks':[88]
})

In [36]:
model.predict(new_student)

array(['Good'], dtype=object)